version: '3.9'

services:

  app:
    
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ./start.sh
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
      

  worker:
    
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: celery --app workers.celery worker --loglevel=info -P solo
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
  
  flower:
    image: mher/flower
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - worker
      - rabbitmq

  db:
    
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - db.env
    
  pgadmin:
    
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - db.env
    depends_on:
      - db

  rabbitmq:
    
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    
  redis:
    
    image: "redis:alpine"
    ports:
      - 6379:6379
      


volumes:
  postgres_data: